# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: Install dependencies
FROM node:lts-alpine AS builder
WORKDIR /app
COPY server/package*.json ./
RUN npm ci --ignore-scripts

# Stage 2: Build runtime image
FROM node:lts-alpine
WORKDIR /app
# Copy node modules
COPY --from=builder /app/node_modules ./node_modules
# Copy server source
COPY server/ ./server

# Ensure index is executable
RUN chmod +x server/index.js

# Entrypoint
ENTRYPOINT ["node", "server/index.js"]
